### ISSUE TITLE
Restoring dynamoDB in another AWS Account

### ISSUE THREAD

**Issue by v3vinvin** [bchew/dynamodump#126]
Hello there.

May I know if it's possible to restore a DynamoDB from AWS Account A to AWS Account B?
The following steps are what I've done:-

1. Backup **DynamoDB from AWS Account A** to **AWS Account B S3 Bucket**.

2. Restoring from **AWS Account B S3 Bucket** to **AWS Account B DynamoDB**.
- Hitting error "ERROR:root:Unable to find file to restore from.  Confirm the name of the table you're restoring.
NoneType: None"
- The DynamoDB Table name that I'm trying to restore already created.

**Comment by v3vinvin** [comment]
Am I required to have a copy of the backup locally in order for the restore through S3 bucket to work?

**Comment by v3vinvin** [comment]
I did have a look at the souce code 
"https://github.com/bchew/dynamodump/blob/54c57e8ce48c86c72b0b5c03c66733a9a4e970a6/dynamodump/dynamodump.py#L208-L213"

But not sure what went wrong.

**Comment by v3vinvin** [comment]
I executed 
```
dynamodump -a "tar" -b "BUCKET_NAME" -m restore -r eu-west-2 -p default -d "DEST_NAME" -s "SOURCE_NAME"
```

**Comment by bchew** [comment]
dynamodump does not support cross-account replication as the AWS profile/credentials used would be for a single account per execution. Depending on the size of your table(s), you could consider a 2 step process of dumping it locally from account A (with account A credentials) and then restoring to account B (with account B credentials).

Alternatively you could consider cross-account replication or data pipeline options:
- https://aws.amazon.com/blogs/database/cross-account-replication-with-amazon-dynamodb/
- https://aws.amazon.com/premiumsupport/knowledge-center/dynamodb-cross-account-migration/

**Comment by v3vinvin** [comment]
Thanks for the reply, @bchew. Thanks for the suggestion, I did end up doing a 3 step process, 

1. Backing up from **Account A DynamoDB** to **Account B S3**. 
2. Downloading it down, extracting it.
3. Restoring it to the **Account B DynamoDB**.
