### ISSUE TITLE
I would like to write an AWS blog about this repo

### ISSUE THREAD

**Issue by onion1984** [bchew/dynamodump#199]
Hi Benny,

I used your repo to help a customer to migrate their DynamoDB database from one account to another. I find it really useful. I would like to write an AWS blog about this tool. I would like to check with you weather it is ok for me to write about it, and I would like you to review and contribute to the blog if that's possible. And I can add you to the co-author. Let me know your thought. You can reach me at tanjicon@amazon.com if you have any queries.

Regards
Tan Jicong

**Comment by bchew** [comment]
@onion1984 sure, that's fine with me! I've just sent you an email on this
